name: bins

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: tstack/lnav-build:1
    steps:
      - uses: actions/checkout@v3
      - name: make
        run: /entrypoint.sh
