name: bins

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make
        uses: addnab/docker-run-action@v3
        with:
          image: tstack/lnav-build:1
          run: /entrypoint.sh
